services:
  # ====================================================================================================================
  # APP
  # ====================================================================================================================
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/sidneyaquino/fiappostech-fastfood:0.4.2
    container_name: fastfood
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: "-XX:+UseContainerSupport -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dspring.backgroundpreinitializer.ignore=true -Dfile.encoding=UTF-8"
      APP_PROFILE: prod
      DB_HOST: sql
      DB_NAME: fastfood
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - sql
    networks:
      - network
    restart: always

  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  sql:
    image: docker.io/chainguard/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: GMT
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - network
    restart: always

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  network:
    driver: bridge
