services:
  # ====================================================================================================================
  # APP
  # ====================================================================================================================
  web:
    image: docker.io/bellsoft/liberica-runtime-container:jdk-21-crac-cds-slim-musl
    container_name: fastfood
    working_dir: /app
    volumes:
      - $PWD:/app
      - ${HOME}/.m2/repository:/root/.m2/repository
    ports:
      - 5005:5005
      - 8080:8080
    environment:
      # APP_PROFILE: prod
      DB_HOST: sql
      DB_NAME: fastfood
      DB_USER: postgres
      DB_PASS: postgres
    entrypoint:
      [
        "sh", "-c",
        "./mvnw spring-boot:run -Dspring.aot.enabled=true -DskipTests"
      ]
    depends_on:
      - sql
    networks:
      - network
    restart: always

  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  sql:
    image: docker.io/chainguard/postgres:latest-dev
    container_name: postgres
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: GMT
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - network
    restart: always

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  network:
    driver: bridge
