# FROM docker.io/bellsoft/liberica-native-image-kit-container:jdk-24-nik-24-glibc AS builder
FROM ghcr.io/graalvm/native-image-community:24 AS builder
WORKDIR /tmp
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN --mount=type=cache,target=/root/.m2 \
   ./mvnw dependency:resolve
COPY src/ src
RUN --mount=type=cache,target=/root/.m2 \
   ./mvnw -Pnative package native:compile-no-fork \
      -DskipTests -Djacoco.skip -Dmaven.compiler.proc=full

FROM docker.io/bellsoft/alpaquita-linux-base:stream-glibc AS runner
# FROM docker.io/library/busybox:glibc AS runner
COPY --chown=755 --from=builder /tmp/target/fastfood /app/app
RUN adduser --disabled-password -u 10001 nonroot \
    && echo "nonroot:x:10001:10001:App User:/:/sbin/nologin" > /etc/minimal-passwd
USER nonroot
SHELL ["/bin/sh", "-c"]
CMD /app/app -Dserver.port=$PORT