version: "3.8"
services:
  # ====================================================================================================================
  # APP
  # ====================================================================================================================
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/sidneyaquino/fiappostech-fastfood:1.1.1
    container_name: fastfood
    ports:
      - $PORT:$PORT
    environment:
      - PORT:${PORT}
      # - APP_PROFILE:prod
    depends_on:
      - sql
    networks:
      - network
    restart: always

  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  sql:
    image: docker.io/library/postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: GMT
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - network
    restart: always

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  network:
    driver: bridge