version: "3.8"
services:
  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  sql:
    image: docker.io/library/postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: GMT
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - network
    restart: always

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  network:
    driver: bridge
