version: "3.8"
services:
  # ====================================================================================================================
  # APP
  # ====================================================================================================================
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sidneyaquino/fiappostech-fastfood:1.0.1      
    container_name: app
    ports:
      - $PORT:$PORT
    environment:
      - PORT:8080
      # - PORT:${PORT}
      # - APP_PROFILE:prod
    depends_on:
      - sql
    networks:
      - network
    restart: always

  # ====================================================================================================================
  # POSTGRES SERVER
  # ====================================================================================================================
  sql:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: GMT
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - network
    restart: always

# ======================================================================================================================
# NET
# ======================================================================================================================
networks:
  network:
    driver: bridge