apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: sidneyaquino-dev
spec:
  rules:
  - host: fastfood.apps.sandbox-m4.g2pi.p1.openshiftapps.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port: 
              number: 8080