@resource=orders
@url={{$dotenv HOST_NAME}}/{{resource}}
@content-type={{$dotenv CONTENT_TYPE}}


### FIND by id
GET {{url}}/75ef3fbb-daaa-4a4f-a868-2881b11f9b11


### FIND All undelivered - RECEIVED + PREPARING + READY
GET {{url}}/undelivered


### FIND by tracking - RECEIVED | PREPARING | READY | FINISHED
GET {{url}}?tracking=RECEIVED


### UPDATE tracking - RECEIVED | PREPARING | READY | FINISHED
PUT {{url}} HTTP/1.1
content-type: {{content-type}}

{
    "orderId": "75ef3fbb-daaa-4a4f-a868-2881b11f9b11",
    "tracking": "FINISHED"
}

### INSERT
POST {{url}} HTTP/1.1
content-type: {{content-type}}

{
    "personalId": "12345678904",
    "products": 
    [
        {
            "produtcId": "4c987ae3-bdb8-4355-86de-2eb3ad2e0fe2",
            "quantity": 1
        },
        {
            "produtcId": "61c100ee-0e8b-41a9-915c-70892d5fac50",
            "quantity": 2
        }
    ]
}