@resource=ordercheckout
@url={{$dotenv HOST_NAME}}/{{resource}}
@content-type={{$dotenv CONTENT_TYPE}}


### UPDATE checkout (fake)
POST {{url}} HTTP/1.1
content-type: {{content-type}}

{
    "orderId": "50c48bd8-ce97-43c2-a71c-0a53436ecc88",
    "value": 22.97
}