@resource=products
@url={{$dotenv HOST_NAME}}/{{resource}}
@content-type={{$dotenv CONTENT_TYPE}}


### FIND by id
GET {{url}}/4c987ae3-bdb8-4355-86de-2eb3ad2e0fe2


### FIND by product category : BURGER - DRINK - SIDE - DESSERT
GET {{url}}?category=DRINK

### UPDATE
PUT {{url}} HTTP/1.1
content-type: {{content-type}}

{
    "productId": "5bc5e89a-4093-4be1-875d-d337c6e273f4",
    "name": "Test Test Berlim",
    "category": "BURGER",
    "value": 29.99
}

### INSERT
POST {{url}} HTTP/1.1
content-type: {{content-type}}

{
   "name": "Test Double Bacon Cheese",
   "description": "Testtest Buger with bacon and cheese",
   "category": "BURGER",
   "value": 12.12
}

### DELETE
DELETE {{url}}/5bc5e89a-4093-4be1-875d-d337c6e273f4