apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment

spec:
  # replicas: 2   # It's in app-hpa.yaml
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      name: app-pod
      labels:
        app: app-pod

    spec:
      containers:
        - name: app-pod-container
          image: docker.io/sidneyaquino/fiappostech-fastfood:0.4.2-SNAPSHOT
          imagePullPolicy: Always # Always/IfNotPresent/Never

          # ENVIROMENT
          envFrom:
            - configMapRef:
                name: app-configmap
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: data-configmap
                  key: DATABASE_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: data-configmap
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: data-configmap
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: data-secret
                  key: POSTGRES_PASSWORD

          # LIFECYCLE
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            # initialDelaySeconds: 150
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            # initialDelaySeconds: 25
            periodSeconds: 5
            failureThreshold: 15
            successThreshold: 1

          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 50
            periodSeconds: 3

          # MACHINE
          resources:
            requests:
              memory: "800Mi" # Cloud
              # memory: "400Mi"  # Local
              cpu: "500m"
            limits:
              memory: "1Gi"   # Cloud
              # memory: "500Mi"  # Local
              cpu: "750m"
          ports:
            - containerPort: 8080